# Generated by Django 3.1.5 on 2021-01-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima_helado',
            options={'verbose_name': 'Ingrediente'},
        ),
    ]
