# Generated by Django 3.1.5 on 2021-01-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizacion', '0002_auto_20210112_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaHelado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('helado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizacion.helado')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizacion.maquina')),
            ],
        ),
    ]
