# Generated by Django 3.1.5 on 2021-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizacion', '0003_maquina_maquinahelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinahelado',
            name='tiempo',
            field=models.IntegerField(default=1),
        ),
    ]
